target 'ENT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ENT

  pod 'SQLite.swift'
  pod 'OpenSans'
  pod 'PMAlertController'
  target 'ENTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ENTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
